### ISSUE TITLE
Support bypassing service discovery & load balance

### ISSUE THREAD

**Issue by jsu216** [networknt/light-router#38]
This issue is created for Jira ticket API-36.
It allows the client of the light-router to specify the service url where the requests should be forwarded to.
Another issue, #362 in light-4j is created to supported the service url header constant.

**Comment by stevehu** [comment]
@jsu216 Welcome to the team. I am looking at the code and can understand what is the purpose but I am afraid that other team members and users won't understand. As this is a new feature, could you please write an RFC document so that other people can understand the rationale behind it. I have created a file with a template at https://github.com/networknt/light-rfcs/blob/master/light-router/0001-bypass-discovery-load-balance.md The same material can be easily converted to the documentation once this is released.

**Comment by jsu216** [comment]
@stevehu I just put some info in. Please review. Thanks.

**Comment by NicholasAzar** [comment]
Keeping this open to track, should be re-closed when the feature is merged

**Comment by jsu216** [comment]
Sorry, I accidentally clicked the close and comment button.

**Comment by stevehu** [comment]
@jsu216 Thanks for the detailed document. The light-router is designed for clients to connect to the services in the cloud with dynamic IPs and ports. If you have static addressed services, why not use light-proxy as it is designed for the use case. For most customers, the light-router is deployed in the DMZ to allow a client to connect to the services in the cloud, if we all the client to specify the URL, then there is a security risk. Could you please provide more information about the use case and we can discuss the best option for it. Something like where the light-router is deployed? where is the service is deployed? If both the service and light-router are deployed in DMZ, why not just connect to the service directly? If the service is in the internal network, then light-proxy is the best option. Thanks.

**Comment by NicholasAzar** [comment]
@stevehu My understanding of the router is to serve as a client proxy for entry to a service mesh. If there is a service at a fixed dns in the mesh (using kubedns for example), that still accounts as scope for the router. No?
To alleviate the security risk, there is inclusion of a whitelist configured in the router to limit the outbound requests a specific client could make. But this is not to say that it is a light-proxy where it only makes outbound requests to a specific service.

**Comment by jsu216** [comment]
@stevehu Some context about the project that I am working on. There will be a so called "consumer proxy" deployed in the Green zone that is responsible not only forwarding the client request from Blue zone (DMZ) to the services in White zone, but also request access token on behave the client in some cases. Also the "consumer proxy" should be able to do both service discovery and static service forward. That's why light-router was chosen here.

**Comment by stevehu** [comment]
@NicholasAzar @jsu216 thanks for the explanation. Both light-router and light-proxy are just a normal microservices with some specific handlers. We also encourage customers to build their own router based on the current implementation so that they can put the aggregation handler into the router. I am trying to understand the use cases and scenarios so that we can come up with the right design. As security is in the discussion, I want to move to the private channel to discuss. @jsu216 what is your email address? I can invite you to the slack.

**Comment by jsu216** [comment]
Closed, per discussion with @zabooma & @NicholasAzar @stevehu, will be addressed elsewhere.
